# Generated by Django 2.2.7 on 2019-11-13 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aviao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='PostoTrabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('aviao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Aviao')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoPostoTrabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio_planejada', models.DateTimeField()),
                ('data_final_planejada', models.DateTimeField()),
                ('data_inicio_real', models.DateTimeField(blank=True, null=True)),
                ('data_final_real', models.DateTimeField(blank=True, null=True)),
                ('posto_trabalho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PostoTrabalho')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Produto')),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='postos',
            field=models.ManyToManyField(through='core.ProdutoPostoTrabalho', to='core.PostoTrabalho'),
        ),
    ]
