# Generated by Django 2.2.7 on 2019-12-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191114_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('data', models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='produtopostotrabalho',
            options={'ordering': ['data_inicio_planejada'], 'verbose_name': 'Posto de Trabalho', 'verbose_name_plural': 'Postos de Trabalho'},
        ),
    ]
